name: PR assignment

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.repository == 'thedjnK/AuTerm'
    steps:
      - name: 'Auto-assign PR'
        uses: thedjnK/auto-assign-issue@712c8ebd726eb08705b4e3c6d180b9d3f4e2f2fa
        with:
          assignees: thedjnK
