name: PR assignment

on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

permissions:
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    if: github.repository == 'thedjnK/AuTerm'
    steps:
      - name: 'Auto-assign PR'
        uses: thedjnK/auto-assign-issue@95f82487ff6a42d36a4256f32fdc833f938cce72
        with:
          assignees: thedjnK
